baseURL: "https://learntechcafe.com"
languageCode: en-CA
title: Learn Tech Cafe
theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true # Addition: tells Hugo to allow raw HTML like <div> tags in Markdown content

params:
  homeInfoParams:
    Title: Cultivating Computer Curiosity
    Content: | 
      Welcome to LearnTechCafe! I'm your host, Dan - and alongside me is my robotic co-host, ABA5! Grab your
      favourite beverage and settle in as we explore computers in a fun, stress-free and beginner-friendly way. This
      blog is for money-savers, lifelong learners and anyone eager to discover what computers can do - and what
      *you* can do with them. In a world where everything costs more, we'll help you build your digital skills and save money
      using free and/or open-source tools. Want to know more about me? [Check out the About page.](/about/)
    RoboQuote: |
      &nbsp;
      <div align="center">| 🤖 <em>Greetings! I’m ABA5, your caffeine-powered study buddy. Let’s make tech make sense.<em></div>
  defaultTheme: auto # to switch between dark or light according to browser theme
  # ShowShareButtons: true---I don't have socials!
  ShowReadingTime: true
  ShowToc: true # Displays table of contents on blog posts
  # ShowBreadCrumbs: true---how does this work? Home > Posts
  ShowPostNavLinks: true # Adds a Previous / Next post suggestion under a single post
  ShowCodeCopyButtons: true
  comments: false # change to true to connect to layouts>partials>comments.html for ad-supported comments via Disqus

taxonomies: # allows Hugo to generate taxonomy pages like /tags/ and /categories/.
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: Search
      name: Search
      url: /search/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 5
    