baseURL: "https://learntechcafe.com"
languageCode: en-CA
title: LearnTechCafe
theme: PaperMod

googleAnalytics: G-XV6PP4886E # Additon to add googleAnalytics. See head.html (search google_analytics) + layout -> partials -> google_analytics.html

markup:
  goldmark:
    renderer:
      unsafe: true # Addition: tells Hugo to allow raw HTML like <div> tags in Markdown content

params:
  homeInfoParams:
    Title: Building Digital Skills on a Budget
    Content: | 
      Welcome to *LearnTechCafe*! I'm your host, Dan - and alongside me is my robotic co-host, A.B.A2! Grab your
      favourite beverage and settle in as we explore computers in a fun, stress-free and beginner-friendly way. This
      blog is for money-savers, lifelong learners and anyone eager to discover what computers can do - and what
      *you* can do with them. In a world where everything costs more, we'll help you build your digital skills and save money
      using free and/or open-source tools. Want to know more about me? [Check out the About page.](/about/)
    RoboQuote: |
      &nbsp;
      <div align="center">| <img src="/images/ABA2-min.png" alt="🤖" style="width:1.1em; height:1.1em; vertical-align: -0.2em; display: inline-block; margin: 0; padding: 0; border: 0;"> <em>Greetings! I’m A.B.A2, your caffeine-powered co-host.<em></div>
  
  assets:
    customCSS: ["css/custom.css"]

  label:
    icon: images/LTC-Logo-only-min.png
    iconHeight: 40
    text: LearnTechCafe

  cover:
    LinkFullImages: true

  defaultTheme: auto # to switch between dark or light according to browser theme
  # ShowShareButtons: true---I don't have socials!
  ShowReadingTime: true
  ShowToc: true # Displays table of contents on blog posts
  ShowBreadCrumbs: true
  ShowPostNavLinks: true # Adds a Previous / Next post suggestion under a single post
  ShowCodeCopyButtons: true
  comments: false # change to true to connect to layouts>partials>comments.html for ad-supported comments via Disqus

taxonomies: # allows Hugo to generate taxonomy pages like /tags/ and /categories/.
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: Search
      name: Search
      url: /search/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 5
    